### PR TITLE
Update fabric to 1.21

### PR DESCRIPTION
**Pull request by JustAlittleWolf**
- Updated gradle, loom and dependencies
- Changed `ResourceLocation` instancing in `ClientHandler` to match the new format
- Changed `BLangGen` because `FabricLanguageProvider` was changed

### CODE REVIEW

**Comment by Guigui220D** [comment]
I'd love to get a release for that!

**Comment by girshcatt** [comment]
how can i compile your code to use it as a mod in minecraft?

**Comment by Guigui220D** [comment]
@girshcatt its fairly easy, just run the gradlew or gradlew.bat script

**Comment by girshcatt** [comment]
> @girshcatt its fairly easy, just run the gradlew or gradlew.bat script

i tried it, gradlew.bat does something, then closes itself

Where can i get compiled .jar mod?

**Comment by 50ap5ud5** [comment]
Hello, thank you for the PR. I have been updating the mod independently with some new changes so I will be publishing it to Modrinth and Curseforge like before. I previously lacked time to work on the mod because of commitments outside of Minecraft modding. The best way to experience the mod is to download it when it is released.

**Pull request closed without merging**
